## Importing All liberay

In [1]:
import sqlite3
import sql
import pandas as pd
import numpy as np

# Connect to a database (creates the database file if it doesn't exist)
cnn = sqlite3.connect('churan_database.db')

## Creating SQL DATA BASE

In [2]:
import sql

# Load the SQL extension
%load_ext sql

# Connect to a SQLite database
%sql sqlite:///churan_database.db

#display style of SQL query results in Jupyter Notebook
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [3]:
%%sql
-- To see the all table in my data base
SELECT name FROM sqlite_master WHERE type='table';

 * sqlite:///churan_database.db
Done.

[('churn_table',), ('WA_Fn-UseC_-Telco-Customer-Churn',)]

## Load The data by pandas and Data Cleaning

In [4]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [5]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [8]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [9]:
# To change the the  TotalCharges  data type into integer
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [10]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [11]:
# To find the percentage of null values in the TotalCharges column
(df.isnull().sum()/len(df))* 100

customerID          0.000000
gender              0.000000
SeniorCitizen       0.000000
Partner             0.000000
Dependents          0.000000
tenure              0.000000
PhoneService        0.000000
MultipleLines       0.000000
InternetService     0.000000
OnlineSecurity      0.000000
OnlineBackup        0.000000
DeviceProtection    0.000000
TechSupport         0.000000
StreamingTV         0.000000
StreamingMovies     0.000000
Contract            0.000000
PaperlessBilling    0.000000
PaymentMethod       0.000000
MonthlyCharges      0.000000
TotalCharges        0.156183
Churn               0.000000
dtype: float64

In [12]:
# Drop the null for total charges
df.dropna(subset=['TotalCharges'], inplace=True)

## Import the data to churan_database.db

In [13]:
# Create a table and insert the data into the database

df.to_sql('WA_Fn-UseC_-Telco-Customer-Churn', cnn, if_exists='replace', index=False)

print(f"Data loaded successfully! Total rows: {len(df)}")

Data loaded successfully! Total rows: 7032

In [14]:

%%sql
-- rename the table name to churn_table
ALTER TABLE 'WA_Fn-UseC_-Telco-Customer-Churn' RENAME TO churn_table;

 * sqlite:///churan_database.db
(sqlite3.OperationalError) there is already another table or index with this name: churn_table
[SQL: -- rename the table name to churn_table
ALTER TABLE 'WA_Fn-UseC_-Telco-Customer-Churn' RENAME TO churn_table;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [15]:
%%sql
select * from Churn_table limit 5;

 * sqlite:///churan_database.db
Done.

[('7590-VHVEG', 'Female', 0, 'Yes', 'No', 1, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 29.85, 29.85, 'No'),
 ('5575-GNVDE', 'Male', 0, 'No', 'No', 34, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Mailed check', 56.95, 1889.5, 'No'),
 ('3668-QPYBK', 'Male', 0, 'No', 'No', 2, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 53.85, 108.15, 'Yes'),
 ('7795-CFOCW', 'Male', 0, 'No', 'No', 45, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'One year', 'No', 'Bank transfer (automatic)', 42.3, 1840.75, 'No'),
 ('9237-HQITU', 'Female', 0, 'No', 'No', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.7, 151.65, 'Yes')]

## Telco Customer Churn - SQL Practice Questions

### 1. Retrieve all columns from the customer churn table

In [16]:
# Python
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [17]:
%%sql
select * from churn_table limit 5;

 * sqlite:///churan_database.db
Done.

[('7590-VHVEG', 'Female', 0, 'Yes', 'No', 1, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 29.85, 29.85, 'No'),
 ('5575-GNVDE', 'Male', 0, 'No', 'No', 34, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Mailed check', 56.95, 1889.5, 'No'),
 ('3668-QPYBK', 'Male', 0, 'No', 'No', 2, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 53.85, 108.15, 'Yes'),
 ('7795-CFOCW', 'Male', 0, 'No', 'No', 45, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'One year', 'No', 'Bank transfer (automatic)', 42.3, 1840.75, 'No'),
 ('9237-HQITU', 'Female', 0, 'No', 'No', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.7, 151.65, 'Yes')]

### 2. Display only customerID, gender, and MonthlyCharges.

In [18]:
# python 

df[['customerID','gender','MonthlyCharges']].head(5)

   customerID  gender  MonthlyCharges
0  7590-VHVEG  Female           29.85
1  5575-GNVDE    Male           56.95
2  3668-QPYBK    Male           53.85
3  7795-CFOCW    Male           42.30
4  9237-HQITU  Female           70.70

In [19]:
%%sql
SELECT 
    customerID, 
    gender, 
    MonthlyCharges 
FROM 
    churn_table LIMIT 5;

 * sqlite:///churan_database.db
Done.

[('7590-VHVEG', 'Female', 29.85),
 ('5575-GNVDE', 'Male', 56.95),
 ('3668-QPYBK', 'Male', 53.85),
 ('7795-CFOCW', 'Male', 42.3),
 ('9237-HQITU', 'Female', 70.7)]

### 3. Find all customers whose Churn status is 'Yes'.

In [20]:
# Python
df[df['Churn'] == 'Yes'].head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
13,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes

In [21]:
%%sql
SELECT 
* 
from 
    churn_table 
        WHERE Churn = 'Yes' LIMIT 5;

 * sqlite:///churan_database.db
Done.

[('3668-QPYBK', 'Male', 0, 'No', 'No', 2, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 53.85, 108.15, 'Yes'),
 ('9237-HQITU', 'Female', 0, 'No', 'No', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.7, 151.65, 'Yes'),
 ('9305-CDSKC', 'Female', 0, 'No', 'No', 8, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 99.65, 820.5, 'Yes'),
 ('7892-POOKP', 'Female', 0, 'Yes', 'No', 28, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 104.8, 3046.05, 'Yes'),
 ('0280-XJGEX', 'Male', 0, 'No', 'No', 49, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 103.7, 5036.3, 'Yes')]

### 4. Show all female customers

In [22]:
# python 
df[df['gender'] == 'Female'].head(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [23]:
%%sql
SELECT * FROM  churn_table WHERE gender ='Female' limit 2;

 * sqlite:///churan_database.db
Done.

[('7590-VHVEG', 'Female', 0, 'Yes', 'No', 1, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 29.85, 29.85, 'No'),
 ('9237-HQITU', 'Female', 0, 'No', 'No', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.7, 151.65, 'Yes')]

### 5.List customers who are senior citizens (SeniorCitizen = 1)

In [24]:
#Python
df[df['SeniorCitizen'] == 1].head(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
20,8779-QRDMV,Male,1,No,No,1,No,No phone service,DSL,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,39.65,39.65,Yes
30,3841-NFECX,Female,1,Yes,No,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,No,No,Two year,Yes,Credit card (automatic),96.35,6766.95,No

In [25]:
%%sql
SELECT * FROM  churn_table WHERE SeniorCitizen =1 limit 2;

 * sqlite:///churan_database.db
Done.

[('8779-QRDMV', 'Male', 1, 'No', 'No', 1, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 39.65, 39.65, 'Yes'),
 ('3841-NFECX', 'Female', 1, 'Yes', 'No', 71, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Two year', 'Yes', 'Credit card (automatic)', 96.35, 6766.95, 'No')]

### 6. Find customers whose monthly charges are greater than 80.

In [26]:
# python
df[df['TotalCharges'] > 80].head(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [27]:
%%sql
SELECT * FROM churn_table WHERE TotalCharges > 80 limit 2;

 * sqlite:///churan_database.db
Done.

[('5575-GNVDE', 'Male', 0, 'No', 'No', 34, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Mailed check', 56.95, 1889.5, 'No'),
 ('3668-QPYBK', 'Male', 0, 'No', 'No', 2, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 53.85, 108.15, 'Yes')]

### 7. Display customers with tenure greater than 24 months

In [28]:
df[df['tenure'] > 24].head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No
12,8091-TTVAX,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,No,Credit card (automatic),100.35,5681.10,No

In [29]:
%%sql
SELECT * FROM churn_table WHERE tenure > 24 limit 2;

 * sqlite:///churan_database.db
Done.

[('5575-GNVDE', 'Male', 0, 'No', 'No', 34, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Mailed check', 56.95, 1889.5, 'No'),
 ('7795-CFOCW', 'Male', 0, 'No', 'No', 45, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'One year', 'No', 'Bank transfer (automatic)', 42.3, 1840.75, 'No')]

### 8. Find customers who have both PhoneService and InternetService

In [30]:
#df[(df['PhoneService'] == 'Yes') & (df['InternetService'].isin(['DSL', 'Fiber optic']))].head() # This is also true
df[(df['PhoneService'] == 'Yes') & (df['InternetService'] != 'No')].head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.40,No

In [31]:
%%sql
SELECT * FROM churn_table WHERE PhoneService = 'Yes' AND InternetService != 'No' LIMIT  2;

 * sqlite:///churan_database.db
Done.

[('5575-GNVDE', 'Male', 0, 'No', 'No', 34, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Mailed check', 56.95, 1889.5, 'No'),
 ('3668-QPYBK', 'Male', 0, 'No', 'No', 2, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 53.85, 108.15, 'Yes')]

### 9. Show customers who use the Fiber optic internet service.

In [32]:
df[df['InternetService'] == 'Fiber optic'].head(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes

In [33]:
%%sql
SELECT * FROM churn_table WHERE InternetService = 'Fiber optic' LIMIT 2;

 * sqlite:///churan_database.db
Done.

[('9237-HQITU', 'Female', 0, 'No', 'No', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.7, 151.65, 'Yes'),
 ('9305-CDSKC', 'Female', 0, 'No', 'No', 8, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 99.65, 820.5, 'Yes')]

### 10. Retrieve customers whose contract type is Month-to-month

In [34]:
# Python
df[df['Contract'] == 'Month-to-month'].head(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [35]:
%%sql
SELECT * FROM churn_table WHERE Contract = 'Month-to-month' LIMIT 2;

 * sqlite:///churan_database.db
Done.

[('7590-VHVEG', 'Female', 0, 'Yes', 'No', 1, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 29.85, 29.85, 'No'),
 ('3668-QPYBK', 'Male', 0, 'No', 'No', 2, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 53.85, 108.15, 'Yes')]

### 11. Display the top 10 customers with the highest monthly charges.

In [36]:

# df.nlargest(10, 'MonthlyCharges') # This is one way to find the top 10 customers with the higest monthly charges
df.sort_values(by='MonthlyCharges', ascending = False).head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
4586,7569-NMZYQ,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),118.75,8672.45,No
2115,8984-HPEMB,Female,0,No,No,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,118.65,8477.60,No
4804,5734-EJKXG,Female,0,No,No,61,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,118.60,7365.70,No
3894,5989-AXPUC,Female,0,Yes,No,68,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Mailed check,118.60,7990.05,No
5127,8199-ZLLSA,Male,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),118.35,7804.15,Yes
6118,9924-JPRMC,Male,0,No,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,118.20,8547.15,No
4610,2889-FPWRM,Male,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),117.80,8684.80,Yes
3205,3810-DVDQQ,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),117.60,8308.90,No
6768,9739-JLPQJ,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),117.50,8670.10,No
4875,2302-ANTDP,Female,1,Yes,No,48,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Month-to-month,No,Electronic check,117.45,5438.90,Yes

In [37]:
%%sql
SELECT * FROM churn_table ORDER BY MonthlyCharges DESC LIMIT 10;

 * sqlite:///churan_database.db
Done.

[('7569-NMZYQ', 'Female', 0, 'Yes', 'Yes', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 118.75, 8672.45, 'No'),
 ('8984-HPEMB', 'Female', 0, 'No', 'No', 71, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 118.65, 8477.6, 'No'),
 ('5989-AXPUC', 'Female', 0, 'Yes', 'No', 68, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Mailed check', 118.6, 7990.05, 'No'),
 ('5734-EJKXG', 'Female', 0, 'No', 'No', 61, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 118.6, 7365.7, 'No'),
 ('8199-ZLLSA', 'Male', 0, 'No', 'No', 67, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 118.35, 7804.15, 'Yes'),
 ('9924-JPRMC', 'Male', 0, 'No', 'No', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 118.2, 8547.15, 'No'),
 ('2889-FPWRM', 'Male', 0, 'Yes', 'No', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 117.8, 8684.8, 'Yes'),
 ('3810-DVDQQ', 'Female', 0, 'Yes', 'Yes', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 117.6, 8308.9, 'No'),
 ('9739-JLPQJ', 'Female', 0, 'Yes', 'Yes', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 117.5, 8670.1, 'No'),
 ('2302-ANTDP', 'Female', 1, 'Yes', 'No', 48, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'No', 'Electronic check', 117.45, 5438.9, 'Yes')]

### 12. Show customers ordered by tenure in descending order

In [38]:
# Two way to find the top 10 customer with the longest tenure
df.sort_values(by = 'tenure', ascending = False).head(10)
df.nlargest(10, 'tenure')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
28,5248-YGIJN,Male,0,Yes,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),90.25,6369.45,No
35,6234-RAAPL,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,No,Yes,Yes,No,Two year,No,Bank transfer (automatic),99.90,7251.70,No
59,5954-BDFSG,Female,0,No,No,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),107.50,7853.70,No
62,0526-SXDJP,Male,0,Yes,No,72,No,No phone service,DSL,Yes,...,Yes,No,No,No,Two year,No,Bank transfer (automatic),42.10,2962.00,No
94,9848-JQJTX,Male,0,No,No,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Two year,Yes,Bank transfer (automatic),100.90,7459.05,No
106,6728-DKUCO,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,No,No,Yes,Yes,One year,Yes,Electronic check,104.15,7303.05,No
109,2848-YXSMW,Male,0,Yes,Yes,72,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),19.40,1363.25,No
127,6734-PSBAW,Male,0,Yes,No,72,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),23.55,1723.95,No
140,3146-MSEGF,Female,1,Yes,Yes,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),88.05,6425.65,No
167,5997-OPVFA,Male,0,Yes,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),89.05,6254.45,No

In [39]:
%%sql
SELECT * FROM churn_table order by tenure DESC LIMIT 10;

 * sqlite:///churan_database.db
Done.

[('5248-YGIJN', 'Male', 0, 'Yes', 'No', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 90.25, 6369.45, 'No'),
 ('6234-RAAPL', 'Female', 0, 'Yes', 'Yes', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Two year', 'No', 'Bank transfer (automatic)', 99.9, 7251.7, 'No'),
 ('5954-BDFSG', 'Female', 0, 'No', 'No', 72, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 107.5, 7853.7, 'No'),
 ('0526-SXDJP', 'Male', 0, 'Yes', 'No', 72, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Two year', 'No', 'Bank transfer (automatic)', 42.1, 2962.0, 'No'),
 ('9848-JQJTX', 'Male', 0, 'No', 'No', 72, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 100.9, 7459.05, 'No'),
 ('6728-DKUCO', 'Female', 0, 'Yes', 'Yes', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 104.15, 7303.05, 'No'),
 ('2848-YXSMW', 'Male', 0, 'Yes', 'Yes', 72, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 19.4, 1363.25, 'No'),
 ('6734-PSBAW', 'Male', 0, 'Yes', 'No', 72, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Bank transfer (automatic)', 23.55, 1723.95, 'No'),
 ('3146-MSEGF', 'Female', 1, 'Yes', 'Yes', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 88.05, 6425.65, 'No'),
 ('5997-OPVFA', 'Male', 0, 'Yes', 'No', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 89.05, 6254.45, 'No')]

###  13.Find the 5 customers with the lowest monthly charges.

In [40]:
# df.sort_values(by = 'MonthlyCharges' , ascending = True).head(5)

df.nsmallest(5, 'MonthlyCharges')[['customerID', 'gender', 'MonthlyCharges']]

      customerID  gender  MonthlyCharges
3719  6823-SIDFQ    Male           18.25
1529  9764-REAFF  Female           18.40
6652  0827-ITJPH    Male           18.55
1156  0621-CXBKL  Female           18.70
6906  9945-PSVIP  Female           18.70

In [41]:
%%sql
SELECT * FROM churn_table ORDER BY MonthlyCharges ASC LIMIT 5;

 * sqlite:///churan_database.db
Done.

[('6823-SIDFQ', 'Male', 0, 'No', 'No', 28, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Credit card (automatic)', 18.25, 534.7, 'No'),
 ('9764-REAFF', 'Female', 0, 'Yes', 'No', 59, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Bank transfer (automatic)', 18.4, 1057.85, 'No'),
 ('0827-ITJPH', 'Male', 0, 'No', 'No', 36, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Credit card (automatic)', 18.55, 689.0, 'No'),
 ('0621-CXBKL', 'Female', 0, 'No', 'No', 53, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 18.7, 1005.7, 'No'),
 ('9945-PSVIP', 'Female', 0, 'Yes', 'Yes', 25, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Mailed check', 18.7, 383.65, 'No')]

### 14. Display customers sorted by TotalCharges from highest to lowest.

In [42]:
# Python
df.sort_values(by ='MonthlyCharges', ascending = False).head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
4586,7569-NMZYQ,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),118.75,8672.45,No
2115,8984-HPEMB,Female,0,No,No,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,118.65,8477.60,No
4804,5734-EJKXG,Female,0,No,No,61,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,118.60,7365.70,No
3894,5989-AXPUC,Female,0,Yes,No,68,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Mailed check,118.60,7990.05,No
5127,8199-ZLLSA,Male,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),118.35,7804.15,Yes

In [43]:
%%sql
SELECT * FROM churn_table ORDER BY MonthlyCharges DESC LIMIT 5;

 * sqlite:///churan_database.db
Done.

[('7569-NMZYQ', 'Female', 0, 'Yes', 'Yes', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 118.75, 8672.45, 'No'),
 ('8984-HPEMB', 'Female', 0, 'No', 'No', 71, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 118.65, 8477.6, 'No'),
 ('5989-AXPUC', 'Female', 0, 'Yes', 'No', 68, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Mailed check', 118.6, 7990.05, 'No'),
 ('5734-EJKXG', 'Female', 0, 'No', 'No', 61, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 118.6, 7365.7, 'No'),
 ('8199-ZLLSA', 'Male', 0, 'No', 'No', 67, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 118.35, 7804.15, 'Yes')]

### 15. Show the first 20 customers whose churn status is Yes.

In [44]:
# Python
df[df['Churn'] == "Yes"].head(20)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
13,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes
18,4190-MFLUW,Female,0,Yes,Yes,10,Yes,No,DSL,No,...,Yes,Yes,No,No,Month-to-month,No,Credit card (automatic),55.20,528.35,Yes
20,8779-QRDMV,Male,1,No,No,1,No,No phone service,DSL,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,39.65,39.65,Yes
22,1066-JKSGK,Male,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.15,20.15,Yes
26,6467-CHFZW,Male,0,Yes,Yes,47,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.35,4749.15,Yes
27,8665-UTDHZ,Male,0,Yes,Yes,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,No,Electronic check,30.20,30.20,Yes
29,8773-HHUOZ,Female,0,No,Yes,17,Yes,No,DSL,No,...,No,No,Yes,Yes,Month-to-month,Yes,Mailed check,64.70,1093.10,Yes
36,6047-YHPVI,Male,0,No,No,5,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,316.90,Yes
38,5380-WJKOV,Male,0,No,No,34,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,106.35,3549.25,Yes
39,8168-UQWWF,Female,0,No,No,11,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),97.85,1105.40,Yes
47,7760-OYPDY,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.65,144.15,Yes
51,9420-LOJKX,Female,0,No,No,15,Yes,No,Fiber optic,Yes,...,No,No,Yes,Yes,Month-to-month,Yes,Credit card (automatic),99.10,1426.40,Yes
53,7495-OOKFY,Female,1,Yes,No,8,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),80.65,633.30,Yes
55,1658-BYGOY,Male,1,No,No,18,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.45,1752.55,Yes
64,5698-BQJOH,Female,0,No,No,9,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,No,Electronic check,94.40,857.25,Yes
80,5919-TMRGD,Female,0,No,Yes,1,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,79.35,79.35,Yes

In [45]:
%%sql
SELECT * FROM churn_table WHERE Churn = 'Yes' LIMIT 20;

 * sqlite:///churan_database.db
Done.

[('3668-QPYBK', 'Male', 0, 'No', 'No', 2, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 53.85, 108.15, 'Yes'),
 ('9237-HQITU', 'Female', 0, 'No', 'No', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.7, 151.65, 'Yes'),
 ('9305-CDSKC', 'Female', 0, 'No', 'No', 8, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 99.65, 820.5, 'Yes'),
 ('7892-POOKP', 'Female', 0, 'Yes', 'No', 28, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 104.8, 3046.05, 'Yes'),
 ('0280-XJGEX', 'Male', 0, 'No', 'No', 49, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 103.7, 5036.3, 'Yes'),
 ('4190-MFLUW', 'Female', 0, 'Yes', 'Yes', 10, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Credit card (automatic)', 55.2, 528.35, 'Yes'),
 ('8779-QRDMV', 'Male', 1, 'No', 'No', 1, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 39.65, 39.65, 'Yes'),
 ('1066-JKSGK', 'Male', 0, 'No', 'No', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.15, 20.15, 'Yes'),
 ('6467-CHFZW', 'Male', 0, 'Yes', 'Yes', 47, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 99.35, 4749.15, 'Yes'),
 ('8665-UTDHZ', 'Male', 0, 'Yes', 'Yes', 1, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 30.2, 30.2, 'Yes'),
 ('8773-HHUOZ', 'Female', 0, 'No', 'Yes', 17, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Mailed check', 64.7, 1093.1, 'Yes'),
 ('6047-YHPVI', 'Male', 0, 'No', 'No', 5, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 69.7, 316.9, 'Yes'),
 ('5380-WJKOV', 'Male', 0, 'No', 'No', 34, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 106.35, 3549.25, 'Yes'),
 ('8168-UQWWF', 'Female', 0, 'No', 'No', 11, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 97.85, 1105.4, 'Yes'),
 ('7760-OYPDY', 'Female', 0, 'No', 'No', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 80.65, 144.15, 'Yes'),
 ('9420-LOJKX', 'Female', 0, 'No', 'No', 15, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 99.1, 1426.4, 'Yes'),
 ('7495-OOKFY', 'Female', 1, 'Yes', 'No', 8, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 80.65, 633.3, 'Yes'),
 ('1658-BYGOY', 'Male', 1, 'No', 'No', 18, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 95.45, 1752.55, 'Yes'),
 ('5698-BQJOH', 'Female', 0, 'No', 'No', 9, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Electronic check', 94.4, 857.25, 'Yes'),
 ('5919-TMRGD', 'Female', 0, 'No', 'Yes', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 79.35, 79.35, 'Yes')]

### 16. Calculate the total number of customers.

In [46]:
#Python

df['customerID'].count() # 1St mathod

print("\n The total Number of customers is: ", df['customerID'].nunique() )# 2St mathod

 The total Number of customers is:  7032

In [47]:
%%sql
SELECT COUNT(customerID) as Total_Cutomers from churn_table;

 * sqlite:///churan_database.db
Done.

[(7032,)]

### 17. Find the average monthly charge of all customers.

In [48]:
# round(df['MonthlyCharges'].sum()/df['customerID'].count(),2) # 2nd mathod

print("the average monthly charge of all customers :",int(df['MonthlyCharges'].mean())) # 2nd mathod

the average monthly charge of all customers : 64

In [49]:
%%sql
SELECT ROUND(AVG(MonthlyCharges),2) as average_monthly_charge FROM churn_table;

 * sqlite:///churan_database.db
Done.

[(64.8,)]

### 18. Calculate the maximum and minimum tenure.

In [50]:
#Python
print(f"The maximum tenure: $ {int(df['tenure'].max())} And the minimum tenure : $ {int(df['tenure'].min())}")

The maximum tenure: $ 72 And the minimum tenure : $ 1

In [51]:
%%sql
SELECT 
    MAX(tenure) as max_tenure, 
    MIN(tenure) as min_tenure 
from 
    churn_table;

 * sqlite:///churan_database.db
Done.

[(72, 1)]

### 19. Find the total revenue generated (SUM(TotalCharges)).

In [52]:
print(f" total revenue generated {df['TotalCharges'].sum():.2f}")

 total revenue generated 16056168.70

In [53]:
%%sql
SELECT SUM(TotalCharges) as total_revenue_generated from churn_table;

 * sqlite:///churan_database.db
Done.

[(16056168.7,)]

### 20. Calculate the average monthly charge for churned customers.

In [54]:
# print(f"the average monthly charge for churned customers: {df.loc[df['Churn'] == 'Yes', 'MonthlyCharges'].mean():.2f}")

a = round(df.groupby('Churn')['MonthlyCharges'].mean(),2)
print(f"The average monthly charge for churned customers: ${a['Yes']}")

The average monthly charge for churned customers: $74.44

In [55]:
%%sql
SELECT 
    Churn, 
    ROUND(AVG(MonthlyCharges), 2) AS average_monthly_charge 
FROM churn_table 
GROUP BY Churn;

 * sqlite:///churan_database.db
Done.

[('No', 61.31), ('Yes', 74.44)]

### 21. Count the number of customers by gender.

In [56]:
# df.groupby('gender').size() # 1st Mathod
print(f"Count the number of customers by {df['gender'].value_counts()}")

Count the number of customers by gender
Male      3549
Female    3483
Name: count, dtype: int64

In [57]:
%%sql
SELECT
    gender,
    count(*) AS Gender_Count
FROM churn_table
GROUP BY gender;

 * sqlite:///churan_database.db
Done.

[('Female', 3483), ('Male', 3549)]

### 22. Find the number of customers for each contract type.

In [58]:
print(f"Count the number of customers by {df['Contract'].value_counts()}")

Count the number of customers by Contract
Month-to-month    3875
Two year          1685
One year          1472
Name: count, dtype: int64

In [59]:
%%sql
SELECT
    Contract,
    count(*) AS Number_of_customer_contract_type
FROM churn_table
GROUP BY Contract;

 * sqlite:///churan_database.db
Done.

[('Month-to-month', 3875), ('One year', 1472), ('Two year', 1685)]

### 23. Calculate the average monthly charge for each internet service type

In [60]:
# df.loc[df['InternetService'], 'MonthlyCharges'].mean()
df.groupby('InternetService')['MonthlyCharges'].mean()

InternetService
DSL            58.088017
Fiber optic    91.500129
No             21.076283
Name: MonthlyCharges, dtype: float64

In [61]:
%%sql
SELECT 
    InternetService, 
    ROUND(AVG(MonthlyCharges), 2) AS average_monthly_charge 
FROM churn_table 
GROUP BY Churn;

 * sqlite:///churan_database.db
Done.

[('DSL', 61.31), ('DSL', 74.44)]

### 24. Count the number of churned and non-churned customers

In [62]:
# Python
churn_Non_churn = df['Churn'].value_counts()

print(f"The number of customers who churned: {churn_Non_churn['Yes']} and The number of customers who did not churn is: {churn_Non_churn['No']}")

The number of customers who churned: 1869 and The number of customers who did not churn is: 5163

In [63]:
%%sql
SELECT Churn, COUNT(*) as Number_of_customers FROM churn_table GROUP BY Churn;

 * sqlite:///churan_database.db
Done.

[('No', 5163), ('Yes', 1869)]

### 25. Find the average tenure of customers grouped by payment method

In [64]:
round(df.groupby('PaymentMethod') ['tenure'].mean(),2)

PaymentMethod
Bank transfer (automatic)    43.71
Credit card (automatic)      43.30
Electronic check             25.17
Mailed check                 21.94
Name: tenure, dtype: float64

In [65]:
%%sql
SELECT PaymentMethod ,round(AVG(tenure),2) as AVG_tenure FROM Churn_table GROUP BY PaymentMethod;

 * sqlite:///churan_database.db
Done.

[('Bank transfer (automatic)', 43.71),
 ('Credit card (automatic)', 43.3),
 ('Electronic check', 25.17),
 ('Mailed check', 21.94)]

### 26. Which payment method has the highest number of churned customers?

In [66]:
result = df[df['Churn'] == 'Yes'].groupby('PaymentMethod')['Churn'].count()
print(result.sort_values(ascending = False))

PaymentMethod
Electronic check             1071
Mailed check                  308
Bank transfer (automatic)     258
Credit card (automatic)       232
Name: Churn, dtype: int64

In [67]:
%%sql
SELECT 
    PaymentMethod, 
    churn, COUNT(churn) as count_churn 
FROM  Churn_table 
    WHERE churn = 'Yes' 
    GROUP BY PaymentMethod 
    ORDER BY count_churn DESC ;

 * sqlite:///churan_database.db
Done.

[('Electronic check', 'Yes', 1071),
 ('Mailed check', 'Yes', 308),
 ('Bank transfer (automatic)', 'Yes', 258),
 ('Credit card (automatic)', 'Yes', 232)]

### 27. Find the churn rate (%) for each contract type.

In [68]:
# 1st We create the Churn_Num column Where Yes = 1, No = 0
df['Churn_Num'] = df['Churn'].map({'Yes': 1, 'No':0})

# . Group by Contract and calculate the mean and multiply by 100
churn_rate_contract = round(df.groupby('Contract')['Churn_Num'].mean() * 100, 2)
print(churn_rate_contract)

Contract
Month-to-month    42.71
One year          11.28
Two year           2.85
Name: Churn_Num, dtype: float64

In [69]:
%%sql
SELECT
    Contract,
    ROUND(sum(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as Churn_Rate_Percentage
FROM churn_table
    GROUP BY 
        Contract;

 * sqlite:///churan_database.db
Done.

[('Month-to-month', 42.71), ('One year', 11.28), ('Two year', 2.85)]

### 28. Calculate total revenue generated by each internet service type.

In [70]:
df.groupby('InternetService')['TotalCharges'].sum()

InternetService
DSL            5121410.85
Fiber optic    9923622.95
No             1011134.90
Name: TotalCharges, dtype: float64

In [71]:
%%sql
SELECT
    InternetService, 
    ROUND(SUM(TotalCharges), 2) AS Total_revenue 
FROM Churn_table
GROUP BY InternetService
ORDER BY Total_revenue DESC;

 * sqlite:///churan_database.db
Done.

[('Fiber optic', 9923622.95), ('DSL', 5121410.85), ('No', 1011134.9)]

In [72]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'Churn_Num'],
      dtype='str')

### 29. Find the top 5 payment methods by total revenue

In [73]:
df.groupby('PaymentMethod')['TotalCharges'].sum().sort_values(ascending=False).head(5)

PaymentMethod
Electronic check             4944903.25
Bank transfer (automatic)    4748279.90
Credit card (automatic)      4671593.35
Mailed check                 1691392.20
Name: TotalCharges, dtype: float64

In [74]:
%%sql
SELECT 
    PaymentMethod, 
    ROUND(SUM(TotalCharges), 2) AS Total_Revenue
FROM 
    churn_table
GROUP BY 
    PaymentMethod
ORDER BY 
    Total_Revenue DESC
LIMIT 5;

 * sqlite:///churan_database.db
Done.

[('Electronic check', 4944903.25),
 ('Bank transfer (automatic)', 4748279.9),
 ('Credit card (automatic)', 4671593.35),
 ('Mailed check', 1691392.2)]

### 30. Which combination of InternetService and Contract has the highest churn count?

In [75]:
# 1. Filter for churned customers first
churned_df = df[df['Churn'] == 'Yes']

# 2. Group by BOTH columns and use .size() to count the rows
# .reset_index() just makes the output look like a clean dataframe!
combo_counts = churned_df.groupby(['InternetService', 'Contract']).size().reset_index(name='ChurnCount')

# 3. Sort to see the highest at the top
result = combo_counts.sort_values(by='ChurnCount', ascending=False)
print(result)

  InternetService        Contract  ChurnCount
3     Fiber optic  Month-to-month        1162
0             DSL  Month-to-month         394
4     Fiber optic        One year         104
6              No  Month-to-month          99
1             DSL        One year          53
5     Fiber optic        Two year          31
2             DSL        Two year          12
7              No        One year           9
8              No        Two year           5

In [76]:
%%sql
SELECT 
    InternetService, 
    Contract, 
    COUNT(*) AS ChurnCount
FROM 
    churn_table
WHERE 
    Churn = 'Yes'
GROUP BY 
    InternetService, 
    Contract
ORDER BY 
    ChurnCount DESC;

 * sqlite:///churan_database.db
Done.

[('Fiber optic', 'Month-to-month', 1162),
 ('DSL', 'Month-to-month', 394),
 ('Fiber optic', 'One year', 104),
 ('No', 'Month-to-month', 99),
 ('DSL', 'One year', 53),
 ('Fiber optic', 'Two year', 31),
 ('DSL', 'Two year', 12),
 ('No', 'One year', 9),
 ('No', 'Two year', 5)]

In [77]:
df.head(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Churn_Num
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,0